import { MigrationInterface, QueryRunner } from "typeorm";

export class MakeTokenNumberNullable1763569421537 implements MigrationInterface {
    name = 'MakeTokenNumberNullable1763569421537'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "certificate" DROP CONSTRAINT "fk_certificate_event"`);
        await queryRunner.query(`ALTER TABLE "certificate" DROP CONSTRAINT "fk_certificate_participant"`);
        await queryRunner.query(`ALTER TABLE "transaction" DROP CONSTRAINT "fk_transaction_event"`);
        await queryRunner.query(`ALTER TABLE "transaction" DROP CONSTRAINT "fk_transaction_participant"`);
        await queryRunner.query(`ALTER TABLE "transaction" DROP CONSTRAINT "fk_transaction_user"`);
        await queryRunner.query(`ALTER TABLE "article" DROP CONSTRAINT "FK_article_author"`);
        await queryRunner.query(`ALTER TABLE "article" DROP CONSTRAINT "FK_article_category"`);
        await queryRunner.query(`DROP INDEX "public"."idx_event_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_event_created_by"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_event_eventType"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_event_isFeatured"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_event_registrationDeadline"`);
        await queryRunner.query(`DROP INDEX "public"."idx_participant_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_participant_event_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_participant_token"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_verification_token"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_reset_token"`);
        await queryRunner.query(`DROP INDEX "public"."idx_kategori_kegiatan_slug"`);
        await queryRunner.query(`DROP INDEX "public"."idx_kategori_slug"`);
        await queryRunner.query(`DROP INDEX "public"."idx_certificate_participant_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_certificate_event_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_certificate_number"`);
        await queryRunner.query(`DROP INDEX "public"."idx_certificate_verification_code"`);
        await queryRunner.query(`DROP INDEX "public"."idx_certificate_issued_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_certificate_template_category"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_certificate_template_isDefault"`);
        await queryRunner.query(`DROP INDEX "public"."idx_transaction_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_transaction_event_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_transaction_participant_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_transaction_order_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_transaction_transaction_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_transaction_payment_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_transaction_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_article_category_slug"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_article_slug"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_article_authorId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_article_categoryId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_article_isPublished"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_article_publishedAt"`);
        await queryRunner.query(`DROP INDEX "public"."idx_testimonial_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_testimonial_sort"`);
        await queryRunner.query(`ALTER TABLE "event" ALTER COLUMN "eventType" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event" ALTER COLUMN "isFeatured" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "participant" ALTER COLUMN "tokenNumber" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "password" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "isEmailVerified" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "isOtpVerified" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "UQ_470355432cc67b2c470c30bef7c" UNIQUE ("googleId")`);
        await queryRunner.query(`ALTER TABLE "kategori_kegiatan" DROP COLUMN "nama_kategori"`);
        await queryRunner.query(`ALTER TABLE "kategori_kegiatan" ADD "nama_kategori" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "kategori_kegiatan" DROP CONSTRAINT "kategori_kegiatan_slug_key"`);
        await queryRunner.query(`ALTER TABLE "kategori_kegiatan" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "kategori_kegiatan" ADD "slug" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "kategori_kegiatan" ADD CONSTRAINT "UQ_64fa1475632e7c00601f22af6eb" UNIQUE ("slug")`);
        await queryRunner.query(`ALTER TABLE "kategori_kegiatan" DROP COLUMN "kategori_logo"`);
        await queryRunner.query(`ALTER TABLE "kategori_kegiatan" ADD "kategori_logo" character varying`);
        await queryRunner.query(`ALTER TABLE "kategori_kegiatan" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "kategori_kegiatan" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "kategori_kegiatan" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "kategori_kegiatan" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "certificate_template" ALTER COLUMN "category" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "certificate_template" ALTER COLUMN "isDefault" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "certificate_template" ALTER COLUMN "isActive" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transaction" ALTER COLUMN "adminFee" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."payment_status_enum" RENAME TO "payment_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."transaction_paymentstatus_enum" AS ENUM('pending', 'paid', 'failed', 'expired', 'cancelled', 'refunded')`);
        await queryRunner.query(`ALTER TABLE "transaction" ALTER COLUMN "paymentStatus" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "transaction" ALTER COLUMN "paymentStatus" TYPE "public"."transaction_paymentstatus_enum" USING "paymentStatus"::"text"::"public"."transaction_paymentstatus_enum"`);
        await queryRunner.query(`ALTER TABLE "transaction" ALTER COLUMN "paymentStatus" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."payment_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "transaction" ALTER COLUMN "paymentStatus" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."payment_method_enum" RENAME TO "payment_method_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."transaction_paymentmethod_enum" AS ENUM('credit_card', 'bank_transfer', 'gopay', 'shopeepay', 'qris', 'ovo', 'dana', 'bca_va', 'bni_va', 'bri_va', 'mandiri_va', 'permata_va', 'cimb_va', 'free')`);
        await queryRunner.query(`ALTER TABLE "transaction" ALTER COLUMN "paymentMethod" TYPE "public"."transaction_paymentmethod_enum" USING "paymentMethod"::"text"::"public"."transaction_paymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_method_enum_old"`);
        await queryRunner.query(`ALTER TABLE "transaction" ALTER COLUMN "isRefunded" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "testimonial" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "testimonial" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "testimonial" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "testimonial" ADD "role" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "testimonial" DROP COLUMN "company"`);
        await queryRunner.query(`ALTER TABLE "testimonial" ADD "company" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "testimonial" ALTER COLUMN "rating" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "testimonial" ALTER COLUMN "isActive" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "testimonial" ALTER COLUMN "sortOrder" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "testimonial" ALTER COLUMN "createdAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "testimonial" ALTER COLUMN "updatedAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "certificate" ADD CONSTRAINT "FK_952260eaece34694dcac14b8f3a" FOREIGN KEY ("participantId") REFERENCES "participant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "certificate" ADD CONSTRAINT "FK_513b73a83f331b11080c3b87902" FOREIGN KEY ("eventId") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction" ADD CONSTRAINT "FK_605baeb040ff0fae995404cea37" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction" ADD CONSTRAINT "FK_f8aba9691e84fbd42400be9ce8a" FOREIGN KEY ("eventId") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction" ADD CONSTRAINT "FK_bd8936cafe154569d33cfc8c7f1" FOREIGN KEY ("participantId") REFERENCES "participant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "article" ADD CONSTRAINT "FK_a9c5f4ec6cceb1604b4a3c84c87" FOREIGN KEY ("authorId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "article" ADD CONSTRAINT "FK_12824e4598ee46a0992d99ba553" FOREIGN KEY ("categoryId") REFERENCES "article_category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "article" DROP CONSTRAINT "FK_12824e4598ee46a0992d99ba553"`);
        await queryRunner.query(`ALTER TABLE "article" DROP CONSTRAINT "FK_a9c5f4ec6cceb1604b4a3c84c87"`);
        await queryRunner.query(`ALTER TABLE "transaction" DROP CONSTRAINT "FK_bd8936cafe154569d33cfc8c7f1"`);
        await queryRunner.query(`ALTER TABLE "transaction" DROP CONSTRAINT "FK_f8aba9691e84fbd42400be9ce8a"`);
        await queryRunner.query(`ALTER TABLE "transaction" DROP CONSTRAINT "FK_605baeb040ff0fae995404cea37"`);
        await queryRunner.query(`ALTER TABLE "certificate" DROP CONSTRAINT "FK_513b73a83f331b11080c3b87902"`);
        await queryRunner.query(`ALTER TABLE "certificate" DROP CONSTRAINT "FK_952260eaece34694dcac14b8f3a"`);
        await queryRunner.query(`ALTER TABLE "testimonial" ALTER COLUMN "updatedAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "testimonial" ALTER COLUMN "createdAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "testimonial" ALTER COLUMN "sortOrder" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "testimonial" ALTER COLUMN "isActive" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "testimonial" ALTER COLUMN "rating" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "testimonial" DROP COLUMN "company"`);
        await queryRunner.query(`ALTER TABLE "testimonial" ADD "company" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "testimonial" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "testimonial" ADD "role" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "testimonial" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "testimonial" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transaction" ALTER COLUMN "isRefunded" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."payment_method_enum_old" AS ENUM('bank_transfer', 'bca_va', 'bni_va', 'bri_va', 'cimb_va', 'credit_card', 'dana', 'free', 'gopay', 'mandiri_va', 'ovo', 'permata_va', 'qris', 'shopeepay')`);
        await queryRunner.query(`ALTER TABLE "transaction" ALTER COLUMN "paymentMethod" TYPE "public"."payment_method_enum_old" USING "paymentMethod"::"text"::"public"."payment_method_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."transaction_paymentmethod_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_method_enum_old" RENAME TO "payment_method_enum"`);
        await queryRunner.query(`ALTER TABLE "transaction" ALTER COLUMN "paymentStatus" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."payment_status_enum_old" AS ENUM('cancelled', 'expired', 'failed', 'paid', 'pending', 'refunded')`);
        await queryRunner.query(`ALTER TABLE "transaction" ALTER COLUMN "paymentStatus" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "transaction" ALTER COLUMN "paymentStatus" TYPE "public"."payment_status_enum_old" USING "paymentStatus"::"text"::"public"."payment_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "transaction" ALTER COLUMN "paymentStatus" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."transaction_paymentstatus_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_status_enum_old" RENAME TO "payment_status_enum"`);
        await queryRunner.query(`ALTER TABLE "transaction" ALTER COLUMN "adminFee" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "certificate_template" ALTER COLUMN "isActive" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "certificate_template" ALTER COLUMN "isDefault" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "certificate_template" ALTER COLUMN "category" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "kategori_kegiatan" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "kategori_kegiatan" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "kategori_kegiatan" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "kategori_kegiatan" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "kategori_kegiatan" DROP COLUMN "kategori_logo"`);
        await queryRunner.query(`ALTER TABLE "kategori_kegiatan" ADD "kategori_logo" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "kategori_kegiatan" DROP CONSTRAINT "UQ_64fa1475632e7c00601f22af6eb"`);
        await queryRunner.query(`ALTER TABLE "kategori_kegiatan" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "kategori_kegiatan" ADD "slug" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "kategori_kegiatan" ADD CONSTRAINT "kategori_kegiatan_slug_key" UNIQUE ("slug")`);
        await queryRunner.query(`ALTER TABLE "kategori_kegiatan" DROP COLUMN "nama_kategori"`);
        await queryRunner.query(`ALTER TABLE "kategori_kegiatan" ADD "nama_kategori" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "UQ_470355432cc67b2c470c30bef7c"`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "isOtpVerified" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "isEmailVerified" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "password" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "participant" ALTER COLUMN "tokenNumber" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event" ALTER COLUMN "isFeatured" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event" ALTER COLUMN "eventType" DROP NOT NULL`);
        await queryRunner.query(`CREATE INDEX "idx_testimonial_sort" ON "testimonial" ("sortOrder") `);
        await queryRunner.query(`CREATE INDEX "idx_testimonial_active" ON "testimonial" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_article_publishedAt" ON "article" ("publishedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_article_isPublished" ON "article" ("isPublished") `);
        await queryRunner.query(`CREATE INDEX "IDX_article_categoryId" ON "article" ("categoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_article_authorId" ON "article" ("authorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_article_slug" ON "article" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_article_category_slug" ON "article_category" ("slug") `);
        await queryRunner.query(`CREATE INDEX "idx_transaction_created_at" ON "transaction" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_transaction_payment_status" ON "transaction" ("paymentStatus") `);
        await queryRunner.query(`CREATE INDEX "idx_transaction_transaction_id" ON "transaction" ("transactionId") `);
        await queryRunner.query(`CREATE INDEX "idx_transaction_order_id" ON "transaction" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "idx_transaction_participant_id" ON "transaction" ("participantId") `);
        await queryRunner.query(`CREATE INDEX "idx_transaction_event_id" ON "transaction" ("eventId") `);
        await queryRunner.query(`CREATE INDEX "idx_transaction_user_id" ON "transaction" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_certificate_template_isDefault" ON "certificate_template" ("isDefault") `);
        await queryRunner.query(`CREATE INDEX "IDX_certificate_template_category" ON "certificate_template" ("category") `);
        await queryRunner.query(`CREATE INDEX "idx_certificate_issued_at" ON "certificate" ("issuedAt") `);
        await queryRunner.query(`CREATE INDEX "idx_certificate_verification_code" ON "certificate" ("verificationCode") `);
        await queryRunner.query(`CREATE INDEX "idx_certificate_number" ON "certificate" ("certificateNumber") `);
        await queryRunner.query(`CREATE INDEX "idx_certificate_event_id" ON "certificate" ("eventId") `);
        await queryRunner.query(`CREATE INDEX "idx_certificate_participant_id" ON "certificate" ("participantId") `);
        await queryRunner.query(`CREATE INDEX "idx_kategori_slug" ON "kategori_kegiatan" ("slug") `);
        await queryRunner.query(`CREATE INDEX "idx_kategori_kegiatan_slug" ON "kategori_kegiatan" ("slug") `);
        await queryRunner.query(`CREATE INDEX "idx_user_reset_token" ON "user" ("resetToken") `);
        await queryRunner.query(`CREATE INDEX "idx_user_verification_token" ON "user" ("verificationToken") `);
        await queryRunner.query(`CREATE INDEX "idx_participant_token" ON "participant" ("tokenNumber") `);
        await queryRunner.query(`CREATE INDEX "idx_participant_event_id" ON "participant" ("eventId") `);
        await queryRunner.query(`CREATE INDEX "idx_participant_user_id" ON "participant" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_event_registrationDeadline" ON "event" ("registrationDeadline") `);
        await queryRunner.query(`CREATE INDEX "IDX_event_isFeatured" ON "event" ("isFeatured") `);
        await queryRunner.query(`CREATE INDEX "IDX_event_eventType" ON "event" ("eventType") `);
        await queryRunner.query(`CREATE INDEX "idx_event_created_by" ON "event" ("createdBy") `);
        await queryRunner.query(`CREATE INDEX "idx_event_date" ON "event" ("date") `);
        await queryRunner.query(`ALTER TABLE "article" ADD CONSTRAINT "FK_article_category" FOREIGN KEY ("categoryId") REFERENCES "article_category"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "article" ADD CONSTRAINT "FK_article_author" FOREIGN KEY ("authorId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction" ADD CONSTRAINT "fk_transaction_user" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction" ADD CONSTRAINT "fk_transaction_participant" FOREIGN KEY ("participantId") REFERENCES "participant"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction" ADD CONSTRAINT "fk_transaction_event" FOREIGN KEY ("eventId") REFERENCES "event"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "certificate" ADD CONSTRAINT "fk_certificate_participant" FOREIGN KEY ("participantId") REFERENCES "participant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "certificate" ADD CONSTRAINT "fk_certificate_event" FOREIGN KEY ("eventId") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
